# Generated by Django 2.1.3 on 2018-12-04 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название баннера')),
                ('text_top', models.CharField(blank=True, max_length=15, verbose_name='Текст на баннере (верхняя строка)')),
                ('text_bottom', models.CharField(blank=True, max_length=15, verbose_name='Текст на баннере (нижняя строка)')),
                ('text_discount', models.CharField(blank=True, max_length=15, verbose_name='Текст на баннере (Размер скидки)')),
                ('text_button', models.CharField(blank=True, max_length=15, verbose_name='Текст на кнопке')),
                ('image', models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название товара')),
                ('full_description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('short_description', models.CharField(max_length=255, unique=True, verbose_name='Краткое описание товара')),
                ('image', models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Наличие')),
                ('ratting', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCategory'),
        ),
    ]
