# Generated by Django 2.1 on 2018-12-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='product', max_length=255, verbose_name='Url товара'),
        ),
    ]
