# Generated by Django 2.1 on 2018-12-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20181205_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_zoom',
            field=models.ImageField(blank=True, upload_to='product_images', verbose_name='Большое изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='text_alt',
            field=models.CharField(default='image', max_length=128, verbose_name='Текст изображения'),
        ),
    ]
