# Generated by Django 2.1 on 2018-12-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20181205_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_1_big',
            field=models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение 1 Большое'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2_big',
            field=models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение 2 Большое'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3_big',
            field=models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение 3 Большое'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4_big',
            field=models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение 4 Большое'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5_big',
            field=models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение 5 Большое'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images', verbose_name='Основное изображение'),
        ),
    ]
