# Generated by Django 2.1 on 2019-01-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190114_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='-', max_length=20, verbose_name='Номер телефона'),
        ),
    ]
