# Generated by Django 2.1 on 2019-01-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratting',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
    ]
