# Generated by Django 2.1 on 2019-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20190115_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='product_images', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание товара'),
        ),
    ]
