# Generated by Django 2.1 on 2018-12-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_basket_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketproduct',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
    ]
