# Generated by Django 2.1 on 2019-01-30 18:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190130_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 18, 17, 26, 191980, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
